name: Build Production

on:
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  API_IMAGE_NAME: ${{ github.repository }}-api
  INGEST_IMAGE_NAME: ${{ github.repository }}-ingest

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      attestations: write
      id-token: write
    outputs:
      build_number: ${{ steps.build_number.outputs.build_number }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate build number
        id: build_number
        run: |
          echo "build_number=${GITHUB_RUN_NUMBER}" >> $GITHUB_OUTPUT

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract API metadata
        id: meta_api
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: ${{ env.REGISTRY }}/${{ env.API_IMAGE_NAME }}
          tags: |
            type=raw,value=${{ steps.build_number.outputs.build_number }}-main
            type=raw,value=${{ github.sha }}

      - name: Extract Ingest metadata
        id: meta_ingest
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: ${{ env.REGISTRY }}/${{ env.INGEST_IMAGE_NAME }}
          tags: |
            type=raw,value=${{ steps.build_number.outputs.build_number }}-main
            type=raw,value=${{ github.sha }}

      - name: Build and push API Docker image
        id: push_api
        uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
        with:
          context: .
          target: api
          build-args: |
            BUILD_NUMBER=${{ steps.build_number.outputs.build_number }}-main
            GITHUB_REPOSITORY=${{ github.repository }}
          push: true
          tags: ${{ steps.meta_api.outputs.tags }}
          labels: ${{ steps.meta_api.outputs.labels }}

      - name: Build and push Ingest Docker image
        id: push_ingest
        uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
        with:
          context: .
          target: ingest
          build-args: |
            BUILD_NUMBER=${{ steps.build_number.outputs.build_number }}-main
            GITHUB_REPOSITORY=${{ github.repository }}
          push: true
          tags: ${{ steps.meta_ingest.outputs.tags }}
          labels: ${{ steps.meta_ingest.outputs.labels }}

      - name: Generate API artifact attestation
        uses: actions/attest-build-provenance@v2
        with:
          subject-name: ${{ env.REGISTRY }}/${{ env.API_IMAGE_NAME}}
          subject-digest: ${{ steps.push_api.outputs.digest }}
          push-to-registry: true

      - name: Generate Ingest artifact attestation
        uses: actions/attest-build-provenance@v2
        with:
          subject-name: ${{ env.REGISTRY }}/${{ env.INGEST_IMAGE_NAME}}
          subject-digest: ${{ steps.push_ingest.outputs.digest }}
          push-to-registry: true
